version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    working_dir: /app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /app
    depends_on:
      - backend 