import React, { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { Loader, Building2, ArrowLeft, FileText, Download } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { apiRequest } from '@/lib/queryClient';
import { Link } from 'wouter';

interface AnalysisResult {
  success: boolean;
  analysis: string;
  company: string;
  analysisType: string;
  model: string;
  timestamp: string;
}

export default function BusinessIntelligence() {
  const [company, setCompany] = useState('');
  const [analysisType, setAnalysisType] = useState('competitor');
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const { toast } = useToast();

  const analysisMutation = useMutation({
    mutationFn: async (data: { company: string; analysisType: string }) => {
      const response = await apiRequest('POST', '/api/business-analysis', data);
      return response.json();
    },
    onSuccess: (data: AnalysisResult) => {
      setResult(data);
      toast({
        title: "Analysis Complete",
        description: `${data.analysisType} analysis for ${data.company} generated successfully`,
      });
    },
    onError: (error: any) => {
      toast({
        title: "Analysis Error",
        description: error.message || "Failed to generate analysis",
        variant: "destructive",
      });
    }
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!company.trim()) return;

    analysisMutation.mutate({
      company: company.trim(),
      analysisType
    });
  };

  const analysisOptions = [
    { value: 'competitor', label: 'Competitor Analysis' },
    { value: 'market', label: 'Market Position' },
    { value: 'swot', label: 'SWOT Analysis' },
    { value: 'financial', label: 'Financial Overview' },
    { value: 'strategic', label: 'Strategic Assessment' }
  ];

  const downloadReport = () => {
    if (!result) return;
    
    const reportContent = `
Business Intelligence Report
============================

Company: ${result.company}
Analysis Type: ${result.analysisType}
Generated: ${new Date(result.timestamp).toLocaleString()}
AI Model: ${result.model}

${result.analysis}

---
Generated by IntelSphere Business Intelligence Platform
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${result.company}_${result.analysisType}_analysis.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 via-blue-950 to-purple-950 p-6">
      <div className="max-w-6xl mx-auto space-y-6">
        
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <Link href="/">
              <Button variant="outline" size="sm" className="text-white border-gray-600">
                <ArrowLeft className="h-4 w-4 mr-2" />
                Back to Dashboard
              </Button>
            </Link>
            <div className="flex items-center space-x-3">
              <Building2 className="h-8 w-8 text-green-400" />
              <h1 className="text-3xl font-bold text-white">Business Intelligence</h1>
            </div>
          </div>
          <Badge variant="outline" className="text-green-400 border-green-400">
            AI-Powered Analysis
          </Badge>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          
          {/* Input Form */}
          <Card className="bg-gray-900/50 border-gray-700">
            <CardHeader>
              <CardTitle className="text-white flex items-center">
                <FileText className="mr-2 h-5 w-5" />
                Generate Analysis
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <form onSubmit={handleSubmit} className="space-y-4">
                <div>
                  <label className="text-sm font-medium text-gray-300 mb-2 block">
                    Company Name
                  </label>
                  <Input
                    value={company}
                    onChange={(e) => setCompany(e.target.value)}
                    placeholder="Enter company name (e.g., Apple, Microsoft, Tesla)"
                    className="bg-gray-800 border-gray-600 text-white"
                  />
                </div>

                <div>
                  <label className="text-sm font-medium text-gray-300 mb-2 block">
                    Analysis Type
                  </label>
                  <Select value={analysisType} onValueChange={setAnalysisType}>
                    <SelectTrigger className="bg-gray-800 border-gray-600 text-white">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-gray-800 border-gray-600">
                      {analysisOptions.map((option) => (
                        <SelectItem key={option.value} value={option.value} className="text-white hover:bg-gray-700">
                          {option.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <Button 
                  type="submit" 
                  disabled={!company.trim() || analysisMutation.isPending}
                  className="w-full bg-green-600 hover:bg-green-700"
                >
                  {analysisMutation.isPending ? (
                    <>
                      <Loader className="mr-2 h-4 w-4 animate-spin" />
                      Generating Analysis...
                    </>
                  ) : (
                    'Generate Business Analysis'
                  )}
                </Button>
              </form>

              {/* Analysis Examples */}
              <div className="space-y-3">
                <h3 className="text-sm font-medium text-gray-300">Analysis Includes:</h3>
                <div className="space-y-2 text-sm text-gray-400">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-green-400 rounded-full" />
                    <span>Market position and competitive landscape</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-blue-400 rounded-full" />
                    <span>Key strengths and growth opportunities</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-yellow-400 rounded-full" />
                    <span>Risk assessment and challenges</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-purple-400 rounded-full" />
                    <span>Strategic recommendations</span>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Results */}
          <Card className="bg-gray-900/50 border-gray-700">
            <CardHeader>
              <div className="flex items-center justify-between">
                <CardTitle className="text-white">Analysis Results</CardTitle>
                {result && (
                  <Button 
                    onClick={downloadReport}
                    variant="outline" 
                    size="sm"
                    className="text-white border-gray-600"
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Download Report
                  </Button>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {!result && !analysisMutation.isPending ? (
                <div className="text-center text-gray-400 py-20">
                  <Building2 className="h-16 w-16 mx-auto mb-4 opacity-50" />
                  <p className="text-lg">Ready to Generate Analysis</p>
                  <p className="text-sm mt-2">Enter a company name and select analysis type to begin</p>
                </div>
              ) : analysisMutation.isPending ? (
                <div className="text-center text-gray-400 py-20">
                  <Loader className="h-16 w-16 mx-auto mb-4 animate-spin opacity-50" />
                  <p className="text-lg">Generating Business Intelligence...</p>
                  <p className="text-sm mt-2">AI is analyzing market data and competitive landscape</p>
                </div>
              ) : result ? (
                <div className="space-y-4">
                  {/* Analysis Header */}
                  <div className="flex items-center justify-between p-4 bg-gray-800/50 rounded-lg">
                    <div>
                      <h3 className="text-lg font-semibold text-white">{result.company}</h3>
                      <p className="text-sm text-gray-400">{result.analysisType} Analysis</p>
                    </div>
                    <div className="text-right">
                      <Badge className="bg-green-500 text-white">{result.model}</Badge>
                      <p className="text-xs text-gray-400 mt-1">
                        {new Date(result.timestamp).toLocaleString()}
                      </p>
                    </div>
                  </div>

                  {/* Analysis Content */}
                  <div className="bg-gray-800/30 p-6 rounded-lg">
                    <div className="prose prose-invert max-w-none">
                      <div className="whitespace-pre-wrap text-gray-200 leading-relaxed">
                        {result.analysis}
                      </div>
                    </div>
                  </div>
                </div>
              ) : null}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}